apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-demo
  namespace: store-demo
spec:
  ingressClassName: nginx
  rules:
    - host: store-demo.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-demo-wordpress
                port:
                  number: 80
