apiVersion: v2
name: store
description: A provisioned WooCommerce store
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: wordpress
    version: 15.2.0
    repository: https://charts.bitnami.com/bitnami
