wordpress:
  image:
    tag: latest
  wordpressUsername: admin
  wordpressPassword: admin123
  wordpressEmail: admin@example.com
  
  extraEnvVars:
    - name: STORE_ID
      value: "{{ .Release.Name }}"
  persistence:
    enabled: true
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  service:
    type: ClusterIP

  mariadb:
    image:
      tag: latest
    auth:
      rootPassword: rootpass123
      password: wordpresspass123
    
  extraVolumes:
    - name: plugin-script
      configMap:
        name: plugin-install-script
        defaultMode: 0777

  extraVolumeMounts:
    - name: plugin-script
      mountPath: /docker-entrypoint-init.d/install-woocommerce.sh
      subPath: install-woocommerce.sh

ingress:
  enabled: true
  host: store.localhost
